version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paneles-mgi-web
    restart: always

    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0

    networks:
      - root_default

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=root_default"

      # HTTPS router
      - "traefik.http.routers.paneles-mgi.rule=Host(`mgipaneles.com.ar`,`www.mgipaneles.com.ar`)"
      - "traefik.http.routers.paneles-mgi.entrypoints=websecure"
      - "traefik.http.routers.paneles-mgi.tls=true"
      - "traefik.http.routers.paneles-mgi.tls.certresolver=letsencrypt"

      # servicio
      - "traefik.http.services.paneles-mgi.loadbalancer.server.port=3000"

      # HTTP → HTTPS redirect
      - "traefik.http.routers.paneles-mgi-http.rule=Host(`mgipaneles.com.ar`,`www.mgipaneles.com.ar`)"
      - "traefik.http.routers.paneles-mgi-http.entrypoints=web"
      - "traefik.http.routers.paneles-mgi-http.middlewares=paneles-mgi-redirect"

      - "traefik.http.middlewares.paneles-mgi-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.paneles-mgi-redirect.redirectscheme.permanent=true"

networks:
  root_default:
    external: true